#!/usr/bin/env python3
"""Inline everything into one self-contained HTML file.

  python3 build.py            -> index.html

The page has no network dependencies: the stylesheet, every module, the
parser worker and both geographic datasets are embedded in the output.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
ASSETS = ROOT / "assets"

MODULES = [
    "00-core.js",
    "10-basemap.js",
    "20-map.js",
    "25-tiles.js",
    "30-analysis.js",
    "40-charts.js",
    "50-ui.js",
]


def js_string(value) -> str:
    """A JS string literal that is safe to sit inside a <script> block."""
    text = value if isinstance(value, str) else json.dumps(value, separators=(",", ":"), ensure_ascii=False)
    return (json.dumps(text, ensure_ascii=False)
            .replace("<", "\\u003c")
            .replace(" ", "\\u2028")
            .replace(" ", "\\u2029"))


def build(out_path: Path) -> Path:
    template = (SRC / "template.html").read_text()
    css = (SRC / "styles.css").read_text()

    basemap = json.loads((ASSETS / "basemap.json").read_text())
    cities = json.loads((ASSETS / "cities.json").read_text())
    worker = (SRC / "js" / "parser.worker.js").read_text()

    parts = [
        "/* Generated by build.py -- edit the files in src/, not this one. */",
        "'use strict';",
        f"const BASEMAP_DATA = JSON.parse({js_string(basemap)});",
        f"const CITY_DATA = JSON.parse({js_string(cities)});",
        f"const PARSER_SOURCE = {js_string(worker)};",
    ]
    for name in MODULES:
        source = (SRC / "js" / name).read_text()
        parts.append(f"/* ---- {name} ---- */\n{source}")

    html = template.replace("/*{{CSS}}*/", css).replace("/*{{JS}}*/", "\n\n".join(parts))
    html = html.replace(
        "</head>",
        f"<!-- Built {date.today().isoformat()} from "
        f"https://github.com/MSMGreen/google-timeline-html -->\n</head>",
        1,
    )
    out_path.write_text(html)
    return out_path


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-o", "--out", default="index.html")
    args = ap.parse_args()

    out = Path(args.out)
    if not out.is_absolute():
        out = ROOT / out
    build(out)
    size = out.stat().st_size
    try:
        shown = out.relative_to(ROOT)
    except ValueError:
        shown = out
    print(f"{shown}: {size / 1024:.0f} KiB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
